### ISSUE TITLE
BUG - Freshness check fails for organization_tag

### ISSUE THREAD

**Issue by wuservices** [fivetran/dbt_zendesk_source#19]
**Are you a current Fivetran customer?** 
Jon Wu, Architect, Paper Culture

**Describe the bug**

`zendesk.organization_tag` fails freshness checks. It appears that it shouldn't be checked.

**Steps to reproduce**
1. Install this package and sync zendesk data
2. Run `dbt source snapshot-freshness`
3. You'll see an error like `ERROR STALE freshness of zendesk.organization_tag`

**Expected behavior**

No freshness error should occur if data sync is working. In my case, it appears that this data just doesn't get updated very often. I noticed that `freshness: null` is configured for `zendesk.organization`. Should that just be copied to `organization_tag` to ignore freshness here too?

**Project variables configuration**

```yml
name: [project-name]
version: 1.0.0
config-version: 2

profile: default
source-paths: [models]
analysis-paths: [analysis]
test-paths: [tests]
data-paths: [data]
macro-paths: [macros]
snapshot-paths: [snapshots]
target-path: target
clean-targets:
  - target
  - dbt_modules

vars:
  zendesk_source:
    zendesk_database: [project]
  # Disable models for Zendesk features we aren't using or syncing
  using_ticket_form_history: False
  using_schedules: False
```

**Package Version**

```yml
packages:
  - package: fishtown-analytics/dbt_utils
    version: 0.6.6
  - package: fivetran/ad_reporting
    version: 0.2.2
  - package: fivetran/facebook_ads
    version: 0.2.1
  - package: fivetran/google_ads
    version: 0.2.1
  - package: fivetran/marketo
    version: 0.4.0
  - package: fivetran/microsoft_ads
    version: 0.2.1
  - package: fivetran/pinterest
    version: 0.3.2
  - package: fivetran/zendesk
    version: 0.5.1
```

**Warehouse**

 
- [x] BigQuery
- [ ] Redshift
- [ ] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Additional context**
Freshness is ignored for `organization`: https://github.com/fivetran/dbt_zendesk_source/blob/master/models/src_zendesk.yml#L130

**Screenshots**

**Please indicate the level of urgency** 

Testing for the first time, but hopefully this is a simple fix.

**Are you interested in contributing to this package?** 

- [ ] Yes, I can do this and open a PR for your review.
- [ ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [X] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.
