### ISSUE TITLE
[Bug] BigQuery "Too Many Nested Views" Error

### ISSUE THREAD

**Issue by nick-data-bilt** [fivetran/dbt_zendesk_source#65]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the issue

All our Fivetran package builds have started failing with the following error:
`Too many nested views/persistent user-defined functions or possible circular reference of views/persistent user-defined functions referenced in query. Only 16 levels of nested views/persistent user-defined functions are allowed.`

A spot check of one of the failing models traces back to the following query (in our environment):
`select
  *
from zendesk_source.stg_zendesk__group_tmp`

Unfortunately I was unable to compile the macro contained in the model definition in this package repo to debug.

Please assist, we have to disable our builds until this is addressed.

### Relevant error log or model output

```shell

```

### Expected behavior

dbt build is successful

### dbt Project configurations
```yml
---

## `config-version` is now optional, see docs: https://docs.getdbt.com/reference/project-configs/config-version
config-version: 2

vars:
  fivetran__remove_empty_table_warnings: true

models:
  +on_schema_change: "sync_all_columns"

  reddit_ads_source: ## add tags for all models in the fivetran/reddit_ads_source package, override materialization to `view` to make real-time
    +tags: reddit_ads
    +materialized: view
  reddit_ads:
    +tags: reddit_ads
    +materialized: view
  google_ads_source: ## add tags for all models in the fivetran/google_ads_source package, override materialization to `view` to make real-time
    +tags: google_ads
    +materialized: view
  google_ads:
    +tags: google_ads
    +materialized: view
  linkedin_source: ## add tags for all models in the fivetran/linkedin_source package, override materialization to `view` to make real-time
    +tags: linkedin
    +materialized: view
  linkedin:
    +tags: linkedin
    +materialized: view
  zendesk_source: ## add tags for all models in the fivetran/zendesk_source package, override materialization to `view` to make real-time
    +tags: [hourly, zendesk]
    ##+materialized: view
  zendesk:
    +tags: [hourly, zendesk]
    ## removing view materialization as final transformations are too complex
    ## +materialized: view

```

### Package versions
```yml
---
packages:
  - package: dbt-labs/dbt_external_tables
    version: ['>=0.10.0', <1.0.0]  ## will automatically bump patches + minor versions but not major versions
    # documentation: https://hub.getdbt.com/dbt-labs/dbt_external_tables/latest/
  - package: dbt-labs/codegen
    version: ['>=0.12.1', <1.0.0]  ## will automatically bump patches + minor versions but not major versions
    # documentation: https://hub.getdbt.com/dbt-labs/codegen/latest/
  - package: dbt-labs/dbt_utils
    version: ['>=1.3.0', <2.0.0]  ## will automatically bump patches + minor versions but not major versions
    # documentation: https://hub.getdbt.com/dbt-labs/dbt_utils/latest/
  - package: metaplane/dbt_expectations
    version: ['>=0.10.8', <1.0.0]  ## will automatically bump patches + minor versions but not major versions
    # documentation: https://hub.getdbt.com/metaplane/dbt_expectations/latest/
    # note that dbt_expectations also installs calogica/dbt_date by default
  - package: fivetran/reddit_ads
    version: ['>=0.3.0', <0.4.0]
    # documentation: https://hub.getdbt.com/fivetran/reddit_ads/latest/
  - package: fivetran/google_ads
    version: [">=0.11.0", "<0.12.0"]
    # documentation: https://hub.getdbt.com/fivetran/google_ads/latest/
  - package: fivetran/google_ads_source
    version: [">=0.11.0", "<0.12.0"]
    # documentation: https://hub.getdbt.com/fivetran/google_ads_source/latest/
  - package: fivetran/fivetran_utils
    version: [">=0.4.0", "<0.5.0"]
    # documentation: https://hub.getdbt.com/fivetran/fivetran_utils/latest/
  - package: fivetran/zendesk_source
    version: [">=0.15.0", "<0.16.0"]
    # documentation: https://hub.getdbt.com/fivetran/zendesk_source/latest/
  - package: fivetran/zendesk
    version: [">=0.21.0", "<0.22.0"]
    # documentation: https://hub.getdbt.com/fivetran/zendesk/latest/
  - package: fivetran/linkedin_source
    version: [">=0.10.0", "<0.11.0"]
    # documentation: https://hub.getdbt.com/fivetran/linkedin_source/latest/
  - package: fivetran/linkedin
    version: [">=0.10.0", "<0.11.0"]
    # documentation: https://hub.getdbt.com/fivetran/linkedin/latest/
```
### What database are you using dbt with?
 
bigquery

### How are you running this dbt package?

dbt Cloud™

### dbt Version

1.9.4

### Are you willing to open a PR to help address this issue?

- [x] Yes.
- [ ] Yes, but I will need assistance.
- [ ] No.
